Repository verida/markdown-notes-demo, pull requests merged in 2021-09, with the labels that each got.

#43 feat: setup eslint configruation
  .eslintrc.json
  .gitignore
  .husky/.gitignore
  .prettierrc.json
  .vscode/settings.json
  package.json
  yarn.lock
Labels: enhancement

#53 feat: Updated UI
  .eslintrc.json
  public/index.html
  src/App.js
  src/api/services.js
  src/assets/icons/Edit.svg
  src/assets/icons/Grid.svg
  src/assets/icons/Import.svg
  src/assets/icons/Plus.svg
  src/assets/icons/Share.svg
  src/assets/icons/Table.svg
  src/assets/icons/Trash.svg
  src/assets/icons/angle_down_filled.svg
  src/assets/icons/arrow_down.svg
  src/assets/icons/external_link.svg
  src/assets/icons/grid_icon.svg
  src/assets/icons/star.svg
  src/assets/icons/star_filled.svg
  src/assets/styles/global.styles.css
  src/components/common/Header.jsx
  src/components/common/NotesActions.jsx
  src/components/common/NotesHeader.jsx
  src/components/common/UserAvatar.jsx
  src/components/common/index.js
  src/components/editorview/NotesViewUI.jsx
  src/components/errorPage/ErrorPage.jsx
  src/components/markdown/RichEditor.jsx
  src/components/modalAlert/ModalAlert.jsx
  src/components/noteTable/NoteTable.jsx
  src/components/notescard/NoteCardDisplay.jsx
  src/components/notescard/NotesCard.jsx
  src/components/popover/Popover.jsx
  src/components/searchBar/SearchBar.jsx
  src/components/sideMenu/SideMenu.jsx
  src/components/sortBarPanel/SortBarPanel.jsx
  src/components/sortBarPanel/components/Filters.jsx
  src/components/swippeableSideBar/SwippeableSideBar.jsx
  src/constants/index.js
  src/contextApi/ContextProvider.js
  src/features/MDEditorForm.jsx
  src/features/ModalPreview.jsx
  src/helpers/Editor.helpers.js
  src/hooks/useActions.js
  src/hooks/useAuthentication.js
  src/index.js
  src/layouts/appLayout.jsx
  src/layouts/layoutDrawer.jsx
  src/libs/index.js
  src/providers/Providers.js
  src/redux/reducers/auth/index.js
  src/redux/reducers/editor/index.js
  src/redux/reducers/index.js
  src/redux/store/index.js
  src/reportWebVitals.js
  src/routes/Routes.js
  src/utils/app.utils.js
  src/utils/store.js
  src/views/Favorites.jsx
  src/views/Home.jsx
Labels: enhancement

#56 Feature/52 update connect screen
  src/App.js
  src/components/common/Header.jsx
  src/components/noteTable/NoteTable.jsx
  src/components/notescard/NoteCardDisplay.jsx
  src/layouts/appLayout.jsx
  src/views/ConnectVault.jsx
  src/views/Editor.jsx
Labels: enhancement

#58 feat: action modals
  src/api/services.js
  src/components/common/editorActions/DeleteNote.jsx
  src/components/common/editorActions/EditName.jsx
  src/components/common/editorActions/NotesActions.jsx
  src/components/common/editorActions/Sharing.jsx
  src/components/common/editorActions/index.js
  src/components/common/index.js
  src/components/modal/AppModal.jsx
  src/components/noteTable/NoteTable.jsx
  src/components/notescard/NoteCardDisplay.jsx
  src/layouts/appLayout.jsx
  src/utils/common.utils.js
  src/views/ConnectVault.jsx
  src/views/Home.jsx
Labels: bug, enhancement, refactor

#59 Feature/test deskktop version
  .env
  .gitignore
  public/schema.json
  src/api/services.js
  src/components/appLoaders/BackDropLoader.jsx
  src/components/common/Header.jsx
  src/components/common/NotesHeader.jsx
  src/components/common/UserAvatar.jsx
  src/components/common/editorActions/EditName.jsx
  src/components/common/editorActions/FavoriteIcon.jsx
  src/components/common/editorActions/NotesActions.jsx
  src/components/index.js
  src/components/modal/AppModal.jsx
  src/components/noteTable/NoteTable.jsx
  src/components/notescard/NoteCardDisplay.jsx
  src/components/sideMenu/SideMenu.jsx
  src/components/snackbar/SnackBar.jsx
  src/constants/index.js
  src/contextApi/ContextProvider.js
  src/layouts/appLayout.jsx
  src/layouts/index.js
  src/layouts/layoutDrawer.jsx
  src/providers/Providers.js
  src/redux/reducers/editor/index.js
  src/theme/index.js
  src/theme/muiBoxShadows.js
  src/theme/muiPalette.js
  src/views/ConnectVault.jsx
  src/views/Editor.jsx
  src/views/Home.jsx
Labels: bug, enhancement

#70 feat: refactor
  package.json
  src/App.js
  src/api/services.js
  src/components/common/Header.jsx
  src/components/common/UserAvatar.jsx
  src/components/common/editorActions/DeleteNote.jsx
  src/components/common/editorActions/EditName.jsx
  src/components/common/editorActions/FavoriteIcon.jsx
  src/components/common/editorActions/NotesActions.jsx
  src/components/markdown/RichEditor.jsx
  src/components/noteTable/NoteTable.jsx
  src/components/notescard/NoteCardDisplay.jsx
  src/contextApi/ContextProvider.js
  src/helpers/Editor.helpers.js
  src/hooks/useConnect.js
  src/index.js
  src/layouts/appLayout.jsx
  src/libs/index.js
  src/providers/Providers.js
  src/redux/reducers/auth/index.js
  src/redux/reducers/editor/index.js
  src/views/ConnectVault.jsx
  src/views/Editor.jsx
  src/views/Home.jsx
  yarn.lock
Labels: bug, enhancement, good first issue, refactor

#73 Feature/markdown preview
  src/components/common/UserAvatar.jsx
  src/components/notescard/NoteCardDisplay.jsx
  src/layouts/appLayout.jsx
  src/redux/reducers/auth/index.js
Labels: bug

#77 update README
  README.md
Labels: documentation

#79 feat: todos
  src/components/common/UserAvatar.jsx
  src/components/common/editorActions/DeleteNote.jsx
  src/layouts/appLayout.jsx
  src/views/Editor.jsx
Labels: bug, enhancement
